### ISSUE TITLE
Allow for different extension

### ISSUE THREAD

**Issue by harleypig** [datamuc/Mojolicious-Plugin-YamlConfig#6]
It doesn't look like the github repo has been updated recently ... the latest version and tag don't match what's on the cpan.

In the register sub, if you change `$conf->{ext} = 'yaml';` to `$conf->{ext} ||= 'yaml';` you can allow for other extensions, such as `yml`.

If you'll update the github repo I'd be glad to provide a pull request with both the code change and documentation change.

**Comment by datamuc** [comment]
Updated, wanna adopt the module?
